/** Offline classroom materials (browser-only — no PHI in git). */

export type SavedMaterial = {
  id: string
  kind: 'token' | 'schedule' | 'social'
  title: string
  studentName: string
  body: string
  createdAt: string
}

const KEY = 'prism_classroom_materials_v1'

export function loadMaterials(): SavedMaterial[] {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw) as SavedMaterial[]
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

export function saveMaterials(list: SavedMaterial[]) {
  localStorage.setItem(KEY, JSON.stringify(list))
}

export function buildLocalSocialStory(studentName: string, topic: string): string {
  const who = studentName || 'the student'
  const t = topic || 'a school routine'
  return `Social Story: ${t}

My name is ${who}.
Sometimes at school I need to practice ${t}.
First, I can look at the steps and take a calm breath.
Next, I try my best and use kind words or a help card if I need support.
Then, when I finish the steps, I can feel proud and ready for what comes next.
It is okay to ask a teacher for help.
I can do hard things one step at a time.

(Local offline draft — optional AI polish when /api/ai-chat is available.)
Generated by PRISM Classroom Materials`
}
