/** Classroom materials library — browser-only (FERPA). */

export type MaterialKind = 'token' | 'schedule' | 'social' | 'comm' | 'behavior'

export type TokenPayload = {
  tokenCount: number
  filled: number
  reward: string
  shape: string
  goalLabel?: string
}

export type SchedulePayload = {
  scheduleType: string
  steps: string[]
  activeStep: number
  /** ISO dates this schedule is planned for (day alerts) */
  scheduledDates: string[]
}

export type SocialPayload = {
  topic: string
  story: string
}

export type CommPayload = {
  cells: string[]
  prompt?: string
  /** session tap log for data */
  taps: { word: string; at: string }[]
}

export type BehaviorPayload = {
  chartType: 'frequency' | 'interval' | 'checkin'
  targetBehavior: string
  intervals?: string[]
  /** tallies keyed by date */
  dailyCounts: Record<string, number>
  scheduledDates: string[]
  linkedFbaSessionId?: string
}

export type MaterialPayload =
  | TokenPayload
  | SchedulePayload
  | SocialPayload
  | CommPayload
  | BehaviorPayload

export type SavedMaterial = {
  id: string
  kind: MaterialKind
  title: string
  studentId: string
  studentName: string
  body: string
  payload: MaterialPayload
  createdAt: string
  updatedAt: string
}

const KEY = 'prism_classroom_materials_v1'

function readList(): SavedMaterial[] {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw) as SavedMaterial[]
    if (!Array.isArray(parsed)) return []
    // migrate legacy rows (name-only, no payload)
    return parsed.map((m) => ({
      ...m,
      studentId: m.studentId || '',
      payload: m.payload || defaultPayload(m.kind, m.body),
      updatedAt: m.updatedAt || m.createdAt,
    }))
  } catch {
    return []
  }
}

function defaultPayload(kind: MaterialKind, body: string): MaterialPayload {
  if (kind === 'token') {
    return { tokenCount: 5, filled: 0, reward: 'preferred activity', shape: '⭐ Stars' }
  }
  if (kind === 'schedule') {
    return { scheduleType: 'Session', steps: body.split('\n').filter(Boolean).slice(0, 8), activeStep: 0, scheduledDates: [] }
  }
  if (kind === 'social') {
    return { topic: 'Routine', story: body }
  }
  if (kind === 'behavior') {
    return {
      chartType: 'frequency',
      targetBehavior: 'Target behavior',
      dailyCounts: {},
      scheduledDates: [],
    }
  }
  return { cells: body.split('\n').filter(Boolean).slice(0, 24), taps: [] }
}

export function loadMaterials(): SavedMaterial[] {
  return readList()
}

export function saveMaterials(list: SavedMaterial[]) {
  localStorage.setItem(KEY, JSON.stringify(list.slice(0, 80)))
}

export function materialsForStudent(studentId: string): SavedMaterial[] {
  return loadMaterials().filter((m) => m.studentId === studentId)
}

export function upsertMaterial(item: SavedMaterial) {
  const list = loadMaterials().filter((m) => m.id !== item.id)
  saveMaterials([item, ...list])
}

export function getMaterial(id: string): SavedMaterial | undefined {
  return loadMaterials().find((m) => m.id === id)
}

export function buildLocalSocialStory(studentName: string, topic: string): string {
  const who = studentName || 'the student'
  const t = topic || 'a school routine'
  return `Social Story: ${t}

My name is ${who}.
Sometimes at school I need to practice ${t}.
First, I can look at the steps and take a calm breath.
Next, I try my best and use kind words or a help card if I need support.
Then, when I finish the steps, I can feel proud and ready for what comes next.
It is okay to ask a teacher for help.
I can do hard things one step at a time.

(Local offline draft — optional AI polish when /api/ai-chat is available.)
Generated by PRISM Classroom Materials`
}

export function speakLocal(text: string) {
  try {
    if (typeof window === 'undefined' || !window.speechSynthesis) return
    window.speechSynthesis.cancel()
    const u = new SpeechSynthesisUtterance(text)
    u.rate = 0.9
    window.speechSynthesis.speak(u)
  } catch {
    /* ignore */
  }
}

/** Materials scheduled for a given day (schedules + behavior charts). */
export function materialsDueOn(dateIso: string): SavedMaterial[] {
  return loadMaterials().filter((m) => {
    if (m.kind === 'schedule') {
      const p = m.payload as SchedulePayload
      return (p.scheduledDates || []).includes(dateIso)
    }
    if (m.kind === 'behavior') {
      const p = m.payload as BehaviorPayload
      return (p.scheduledDates || []).includes(dateIso)
    }
    return false
  })
}
