import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/PageShell'
import { useDistrictProfile } from '../../lib/district-profiles/useDistrictProfile'
import { useStudents } from '../../lib/students/useStudents'
import { statusBadgeClass, daysUntil } from '../../lib/students/normalizeStudent'
import { buildDashboardAlerts } from '../../lib/compliance/buildDashboardAlerts'
import { loadProbeSessions } from '../../lib/progress-monitoring/store'
import { loadSoapNotes } from '../../lib/session-notes/store'
import { loadTodos, saveTodos, type TodoItem } from '../../lib/dashboard/todoStore'

function formatTimer(totalSec: number) {
  const h = String(Math.floor(totalSec / 3600)).padStart(2, '0')
  const m = String(Math.floor((totalSec % 3600) / 60)).padStart(2, '0')
  const s = String(totalSec % 60).padStart(2, '0')
  return `${h}:${m}:${s}`
}

export function DashboardPage() {
  const { students } = useStudents()
  const { profile } = useDistrictProfile()
  const [timerSec, setTimerSec] = useState(0)
  const [running, setRunning] = useState(false)
  const [agenda, setAgenda] = useState('Introductions\nData review\nNext steps')
  const [summary, setSummary] = useState('')
  const [todos, setTodos] = useState<TodoItem[]>(() => loadTodos())
  const [todoDraft, setTodoDraft] = useState('')

  useEffect(() => {
    if (!running) return
    const id = window.setInterval(() => setTimerSec((n) => n + 1), 1000)
    return () => window.clearInterval(id)
  }, [running])

  const today = useMemo(
    () =>
      new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        timeZone: 'America/Denver',
      }),
    [],
  )

  const alerts = useMemo(
    () =>
      buildDashboardAlerts({
        students,
        sessions: loadProbeSessions(),
        soapNotes: loadSoapNotes(),
        nomLeadTimeDays: profile.rules.nomLeadTimeDays,
        serviceLogHours: profile.rules.serviceLogHours,
        iepSystem: profile.iepSystem,
      }),
    [students, profile.rules.nomLeadTimeDays, profile.rules.serviceLogHours, profile.iepSystem],
  )

  const stats = useMemo(() => {
    const overdue = students.filter((s) => s.status === 'Overdue')
    const upcoming = students.filter((s) => {
      const due = s.hasIEP ? s.iepDue : s.section504Due
      const d = daysUntil(due || undefined)
      return d != null && d >= 0 && d <= 45
    })
    const pmDue = alerts.filter((a) => a.category === 'progress').length
    const nomDue = alerts.filter((a) => a.category === 'nom').length
    return {
      total: students.length,
      overdue: overdue.length,
      upcoming: upcoming.length,
      with504: students.filter((s) => s.has504).length,
      withMll: students.filter((s) => s.hasMLL).length,
      pmDue,
      nomDue,
    }
  }, [students, alerts])

  function stopMeeting() {
    setRunning(false)
    const text = `MEETING SUMMARY (local draft — ${profile.name})
Duration: ${formatTimer(timerSec)}
Agenda:
${agenda}

Action items:
- [ ] Confirm NOM / follow-ups in ${profile.iepSystem} (no live sync)
- [ ] Enter service notes within ${profile.rules.serviceLogHours}h if sessions occurred

Generated by PRISM Dashboard`
    setSummary(text)
  }

  function persistTodos(next: TodoItem[]) {
    setTodos(next)
    saveTodos(next)
  }

  function addTodo() {
    const text = todoDraft.trim()
    if (!text) return
    persistTodos([
      { id: `td-${Date.now()}`, text, done: false, createdAt: new Date().toISOString() },
      ...todos,
    ])
    setTodoDraft('')
  }

  return (
    <PageShell
      title="🏠 Main Dashboard"
      description={`AI SPED Secretary HQ for ${profile.name}. Compliance hub pulls annuals, NOM windows, progress probes, and SOAP reminders from your local stores.`}
    >
      <p className="mb-3 text-sm font-semibold text-[var(--text)]">{today}</p>

      <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-7">
        {[
          { label: 'Students', value: stats.total, color: 'text-[var(--accent)]' },
          { label: 'Overdue', value: stats.overdue, color: 'text-red-600' },
          { label: 'Due ≤45d', value: stats.upcoming, color: 'text-amber-600' },
          { label: 'PM due', value: stats.pmDue, color: 'text-orange-600' },
          { label: 'NOM watch', value: stats.nomDue, color: 'text-rose-600' },
          { label: '504 plans', value: stats.with504, color: 'text-indigo-600' },
          { label: 'MLL', value: stats.withMll, color: 'text-teal-600' },
        ].map((c) => (
          <div
            key={c.label}
            className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-3 text-center shadow-card"
          >
            <p className={`font-mono text-2xl font-bold ${c.color}`}>{c.value}</p>
            <p className="text-xs text-[var(--subtext)]">{c.label}</p>
          </div>
        ))}
      </div>

      <div className="mb-3 grid gap-3 lg:grid-cols-2">
        <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <h2 className="font-heading text-sm font-bold">Meeting timer</h2>
          <p className="mt-1 font-mono text-3xl font-bold text-[var(--accent)]">{formatTimer(timerSec)}</p>
          <label className="mt-2 block text-xs font-semibold">
            Agenda (one item per line)
            <textarea
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
              rows={3}
              value={agenda}
              onChange={(e) => setAgenda(e.target.value)}
            />
          </label>
          <div className="mt-2 flex flex-wrap gap-2">
            <button
              type="button"
              className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
              onClick={() => setRunning(true)}
              disabled={running}
            >
              Start
            </button>
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              onClick={stopMeeting}
            >
              Stop + draft summary
            </button>
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              onClick={() => {
                setRunning(false)
                setTimerSec(0)
                setSummary('')
              }}
            >
              Reset
            </button>
            {summary && (
              <button
                type="button"
                className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
                onClick={() => void navigator.clipboard.writeText(summary)}
              >
                Copy summary
              </button>
            )}
          </div>
          {summary && (
            <pre className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--slate)] p-3 text-[10px]">
              {summary}
            </pre>
          )}
        </section>

        <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <h2 className="font-heading text-sm font-bold">Quick actions</h2>
          <div className="mt-3 grid gap-2 sm:grid-cols-2">
            {[
              { to: '/reminders', label: '📨 Enrich Reminders' },
              { to: '/contacts', label: '📞 Parent Contact Log' },
              { to: '/progress', label: '📈 Progress Monitoring' },
              { to: '/caseload', label: '👤 Caseload / SOAP' },
              { to: '/binder', label: '📁 Caseload Binder PDF' },
              { to: '/game', label: '🎲 Motivation Game' },
              { to: '/generation', label: '✨ Generation Studio' },
              { to: '/tools', label: '🧮 LRE / Age Tools' },
              { to: '/fba', label: '🔍 FBA / BIP' },
              { to: '/evaluations', label: '📊 Eval Tracker' },
              { to: '/templates', label: '🎨 Templates / Materials' },
              { to: '/mtss', label: '📋 MTSS / DAT' },
              { to: '/students', label: '🧩 Student Tiles' },
              { to: '/district', label: '🏛️ District Profile' },
            ].map((l) => (
              <Link
                key={l.to}
                to={l.to}
                className="rounded-xl border border-[var(--border)] bg-[var(--slate)] px-3 py-3 text-xs font-semibold text-[var(--text)] hover:border-[var(--accent)]"
              >
                {l.label}
              </Link>
            ))}
          </div>
          <p className="mt-3 text-[10px] text-[var(--subtext)]">
            Live Azure still serves <code>deploy/</code>. AI routes need Functions + keys when Azure
            recovers — see docs/ops/AZURE_RECOVERY_CHECKLIST.md.
          </p>
        </section>
      </div>

      <div className="mb-3 grid gap-3 lg:grid-cols-2">
        <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <div className="flex items-center justify-between gap-2">
            <h2 className="font-heading text-sm font-bold">Compliance hub</h2>
            <span className="text-[10px] text-[var(--subtext)]">{alerts.length} active</span>
          </div>
          <div className="mt-3 max-h-80 space-y-2 overflow-y-auto">
            {alerts.length === 0 ? (
              <p className="text-xs text-[var(--subtext)]">
                No overdue annuals, NOM windows, or progress probes needing attention.
              </p>
            ) : (
              alerts.map((a) => (
                <Link
                  key={a.id}
                  to={a.href}
                  className={`block rounded-lg border-l-4 p-2 text-xs hover:opacity-90 ${
                    a.tone === 'danger'
                      ? 'border-l-red-500 bg-[var(--coral)]'
                      : a.tone === 'warn'
                        ? 'border-l-amber-500 bg-[var(--sun)]'
                        : 'border-l-sky-500 bg-[var(--sky)]'
                  }`}
                >
                  {a.text}
                </Link>
              ))
            )}
          </div>
        </section>

        <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <h2 className="font-heading text-sm font-bold">My to-do</h2>
          <div className="mt-2 flex gap-2">
            <input
              className="flex-1 rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
              placeholder="Add a task…"
              value={todoDraft}
              onChange={(e) => setTodoDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') addTodo()
              }}
            />
            <button
              type="button"
              className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
              onClick={addTodo}
            >
              Add
            </button>
          </div>
          <ul className="mt-3 space-y-2">
            {!todos.length && (
              <li className="text-xs text-[var(--subtext)]">No tasks yet — add NOM, probes, or calls.</li>
            )}
            {todos.map((t) => (
              <li key={t.id} className="flex items-center gap-2 text-xs">
                <input
                  type="checkbox"
                  checked={t.done}
                  onChange={() =>
                    persistTodos(todos.map((x) => (x.id === t.id ? { ...x, done: !x.done } : x)))
                  }
                />
                <span className={t.done ? 'text-[var(--subtext)] line-through' : ''}>{t.text}</span>
                <button
                  type="button"
                  className="ml-auto text-[10px] text-red-600"
                  onClick={() => persistTodos(todos.filter((x) => x.id !== t.id))}
                >
                  ×
                </button>
              </li>
            ))}
          </ul>
        </section>
      </div>

      <section className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
        <h2 className="font-heading mb-3 text-sm font-bold">Caseload snapshot</h2>
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-[var(--border)] text-[var(--subtext)]">
              <th className="p-2">Student</th>
              <th className="p-2">Programs</th>
              <th className="p-2">Due</th>
              <th className="p-2">Status</th>
            </tr>
          </thead>
          <tbody>
            {students.slice(0, 8).map((s) => {
              const due = s.hasIEP ? s.iepDue : s.section504Due || ''
              return (
                <tr key={s.id} className="border-b border-[var(--border)] last:border-0">
                  <td className="p-2 font-semibold">{s.name}</td>
                  <td className="p-2">
                    {[s.hasIEP ? 'IEP' : null, s.has504 ? '504' : null, s.hasMLL ? 'MLL' : null]
                      .filter(Boolean)
                      .join(' · ')}
                  </td>
                  <td className="p-2 font-mono">{due || '—'}</td>
                  <td className="p-2">
                    <span
                      className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${statusBadgeClass(s.status)}`}
                    >
                      {s.status}
                    </span>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </section>
    </PageShell>
  )
}
