/** Parent / family contact log — browser-only (FERPA). */

export type ContactMethod = 'phone' | 'email' | 'in-person' | 'message' | 'other'

export type ParentContact = {
  id: string
  studentId: string
  date: string
  method: ContactMethod
  contactName: string
  notes: string
  followUpNeeded: boolean
  createdAt: string
}

const KEY = 'prism_parent_contacts_v1'

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key)
    if (!raw) return fallback
    return (JSON.parse(raw) as T) ?? fallback
  } catch {
    return fallback
  }
}

export function loadParentContacts(): ParentContact[] {
  const list = readJson<ParentContact[]>(KEY, [])
  return Array.isArray(list) ? list : []
}

export function saveParentContacts(list: ParentContact[]) {
  localStorage.setItem(KEY, JSON.stringify(list))
}

export function formatContactForCopy(c: ParentContact, studentName: string): string {
  return `PARENT CONTACT LOG
Student: ${studentName}
Date: ${c.date}
Method: ${c.method}
Contact: ${c.contactName || '—'}
Follow-up needed: ${c.followUpNeeded ? 'Yes' : 'No'}
Notes: ${c.notes || '—'}

Generated by PRISM · enter official documentation in your SoR as required`
}
