import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/PageShell'
import { useDistrictProfile } from '../../lib/district-profiles/useDistrictProfile'
import { useStudents } from '../../lib/students/useStudents'
import { BUILTIN_FORMS, fillTemplateBody } from '../../lib/templates/catalog'
import { loadProbeSessions } from '../../lib/progress-monitoring/store'
import { loadSoapNotes } from '../../lib/session-notes/store'
import {
  defaultPacket,
  loadPrepPackets,
  PREP_CHECKS,
  savePrepPackets,
  type MeetingPrepPacket,
  type PrepCheckId,
} from '../../lib/meeting-prep/store'

export function MeetingPrepPage() {
  const { students } = useStudents()
  const { profile } = useDistrictProfile()
  const [packets, setPackets] = useState<MeetingPrepPacket[]>(() => loadPrepPackets())
  const [packet, setPacket] = useState<MeetingPrepPacket>(() => defaultPacket('', ''))
  const [toast, setToast] = useState('')

  const student = useMemo(
    () => students.find((s) => s.id === packet.studentId),
    [students, packet.studentId],
  )

  const nomDays = profile.rules.nomLeadTimeDays

  function flash(msg: string) {
    setToast(msg)
    window.setTimeout(() => setToast(''), 2200)
  }

  function persist(next: MeetingPrepPacket) {
    setPacket(next)
    const list = [next, ...packets.filter((p) => p.id !== next.id)].slice(0, 40)
    setPackets(list)
    savePrepPackets(list)
  }

  function selectStudent(id: string) {
    const s = students.find((x) => x.id === id)
    const existing = packets.find((p) => p.studentId === id)
    if (existing) {
      setPacket(existing)
      return
    }
    persist(
      defaultPacket(id, s?.name || '', s?.meetingDate || ''),
    )
  }

  function toggle(id: PrepCheckId) {
    persist({
      ...packet,
      checks: { ...packet.checks, [id]: !packet.checks[id] },
    })
  }

  function assemblePacket() {
    if (!student) {
      flash('Select a student')
      return
    }
    const agendaTpl = BUILTIN_FORMS.find((f) => f.id === 'iep-agenda')
    const nomTpl = BUILTIN_FORMS.find((f) => f.id === 'nom')
    const agenda = agendaTpl ? fillTemplateBody(agendaTpl.body, student) : ''
    const nom = nomTpl ? fillTemplateBody(nomTpl.body, student) : ''

    const probes = loadProbeSessions()
      .filter((p) => p.studentId === student.id)
      .slice(0, 5)
    const soap = loadSoapNotes()
      .filter((n) => n.studentId === student.id)
      .slice(0, 5)

    const checklist = PREP_CHECKS.map(
      (c) => `- [${packet.checks[c.id] ? 'x' : ' '}] ${c.label}`,
    ).join('\n')

    const text = `IEP / MEETING PREP PACKET — ${profile.name}
Student: ${student.name} (${student.grade})
Purpose: ${packet.purpose}
Meeting date: ${packet.meetingDate || student.meetingDate || 'TBD'}
NOM lead time: ${nomDays} calendar days (legal notice in ${profile.iepSystem})
MLL / interpreter: ${student.hasMLL ? `yes · ${student.homeLanguage || 'language TBD'}${student.interpreterNeeded ? ' · interpreter needed' : ''}` : 'n/a'}

CHECKLIST
${checklist}

RECENT PROBES
${probes.length ? probes.map((p) => `· ${p.date} ${p.label} — ${p.scorePercent}%`).join('\n') : '· none stored'}

RECENT SOAP / SERVICE DATES
${soap.length ? soap.map((n) => `· ${n.date}`).join('\n') : '· none stored'}

NOTES
${packet.notes || '—'}

—— AGENDA DRAFT ——
${agenda}

—— NOM DRAFT (Companion: finalize in ${profile.iepSystem}) ——
${nom}

Generated by PRISM Meeting Prep · no live Enrich sync · human review required`

    persist({ ...packet, packetText: text, checks: { ...packet.checks, agenda: true } })
    flash('Packet assembled — Copy or Print')
  }

  const doneCount = PREP_CHECKS.filter((c) => packet.checks[c.id]).length

  return (
    <PageShell
      title="📋 Meeting Prep"
      description={`Assemble an IEP meeting packet: NOM checklist (${nomDays}d), progress/SOAP pull, agenda + NOM drafts from templates. Companion: Copy into ${profile.iepSystem}.`}
    >
      {toast && (
        <div className="mb-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white">
          {toast}
        </div>
      )}

      <section className="mb-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
        <div className="grid gap-3 md:grid-cols-2">
          <label className="text-xs font-semibold">
            Student
            <select
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.studentId}
              onChange={(e) => selectStudent(e.target.value)}
            >
              <option value="">Select…</option>
              {students.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                  {s.meetingDate ? ` · meet ${s.meetingDate}` : ''}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs font-semibold">
            Meeting date
            <input
              type="date"
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.meetingDate}
              onChange={(e) => persist({ ...packet, meetingDate: e.target.value })}
            />
          </label>
          <label className="text-xs font-semibold md:col-span-2">
            Purpose
            <input
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.purpose}
              onChange={(e) => persist({ ...packet, purpose: e.target.value })}
            />
          </label>
        </div>

        <p className="mt-3 text-xs font-semibold">
          Prep checklist ({doneCount}/{PREP_CHECKS.length})
        </p>
        <ul className="mt-2 space-y-1">
          {PREP_CHECKS.map((c) => (
            <li key={c.id}>
              <label className="flex items-center gap-2 text-xs">
                <input
                  type="checkbox"
                  checked={packet.checks[c.id]}
                  onChange={() => toggle(c.id)}
                />
                {c.label}
              </label>
            </li>
          ))}
        </ul>

        <label className="mt-3 block text-xs font-semibold">
          Notes
          <textarea
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
            rows={2}
            value={packet.notes}
            onChange={(e) => persist({ ...packet, notes: e.target.value })}
          />
        </label>

        <div className="mt-3 flex flex-wrap gap-2">
          <button
            type="button"
            className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
            onClick={assemblePacket}
          >
            Assemble packet
          </button>
          <button
            type="button"
            className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
            disabled={!packet.packetText}
            onClick={() =>
              void navigator.clipboard.writeText(packet.packetText).then(() => flash('Copied'))
            }
          >
            Copy packet
          </button>
          <button
            type="button"
            className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
            disabled={!packet.packetText}
            onClick={() => window.print()}
          >
            Print
          </button>
          <Link to="/reminders" className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold">
            Enrich Reminders →
          </Link>
          <Link to="/planner" className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold">
            Weekly Planner →
          </Link>
        </div>

        {packet.packetText && (
          <pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--slate)] p-3 text-[10px]">
            {packet.packetText}
          </pre>
        )}
      </section>
    </PageShell>
  )
}
