import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/PageShell'
import { useDistrictProfile } from '../../lib/district-profiles/useDistrictProfile'
import { useStudents } from '../../lib/students/useStudents'
import { BUILTIN_FORMS, fillTemplateBody } from '../../lib/templates/catalog'
import { loadProbeSessions } from '../../lib/progress-monitoring/store'
import { loadSoapNotes } from '../../lib/session-notes/store'
import {
  AGENDA_SECTIONS,
  defaultPacket,
  formatAgendaSections,
  loadPrepPackets,
  PREP_CHECKS,
  savePrepPackets,
  type AgendaSectionId,
  type MeetingPrepPacket,
  type PrepCheckId,
} from '../../lib/meeting-prep/store'

export function MeetingPrepPage() {
  const { students } = useStudents()
  const { profile } = useDistrictProfile()
  const [packets, setPackets] = useState<MeetingPrepPacket[]>(() => loadPrepPackets())
  const [packet, setPacket] = useState<MeetingPrepPacket>(() => defaultPacket('', ''))
  const [toast, setToast] = useState('')

  const student = useMemo(
    () => students.find((s) => s.id === packet.studentId),
    [students, packet.studentId],
  )

  const nomDays = profile.rules.nomLeadTimeDays

  function flash(msg: string) {
    setToast(msg)
    window.setTimeout(() => setToast(''), 2200)
  }

  function persist(next: MeetingPrepPacket) {
    setPacket(next)
    const list = [next, ...packets.filter((p) => p.id !== next.id)].slice(0, 40)
    setPackets(list)
    savePrepPackets(list)
  }

  function selectStudent(id: string) {
    const s = students.find((x) => x.id === id)
    const existing = packets.find((p) => p.studentId === id)
    if (existing) {
      setPacket(existing)
      return
    }
    const next = defaultPacket(id, s?.name || '', s?.meetingDate || '')
    if (s?.goals?.length) {
      next.agendaSections.goals = s.goals.map((g) => `· ${g}`).join('\n')
    }
    if (s?.accommodations?.length) {
      next.agendaSections.accommodations = s.accommodations.map((a) => `· ${a}`).join('\n')
    }
    persist(next)
  }

  function toggle(id: PrepCheckId) {
    persist({
      ...packet,
      checks: { ...packet.checks, [id]: !packet.checks[id] },
    })
  }

  function setSection(id: AgendaSectionId, value: string) {
    persist({
      ...packet,
      agendaSections: { ...packet.agendaSections, [id]: value },
    })
  }

  function assemblePacket() {
    if (!student) {
      flash('Select a student')
      return
    }
    const agendaTpl = BUILTIN_FORMS.find((f) => f.id === 'iep-agenda')
    const nomTpl = BUILTIN_FORMS.find((f) => f.id === 'nom')
    const filledAgenda = formatAgendaSections(packet.agendaSections)
    const agendaFallback = agendaTpl ? fillTemplateBody(agendaTpl.body, student) : ''
    const nom = nomTpl ? fillTemplateBody(nomTpl.body, student) : ''

    const probes = loadProbeSessions()
      .filter((p) => p.studentId === student.id)
      .slice(0, 5)
    const soap = loadSoapNotes()
      .filter((n) => n.studentId === student.id)
      .slice(0, 5)

    const checklist = PREP_CHECKS.map(
      (c) => `- [${packet.checks[c.id] ? 'x' : ' '}] ${c.label}`,
    ).join('\n')

    const text = `IEP / MEETING PREP PACKET — ${profile.name}
Student: ${student.name} (${student.grade})
Purpose: ${packet.purpose}
Meeting date: ${packet.meetingDate || student.meetingDate || 'TBD'}
NOM lead time: ${nomDays} calendar days (legal notice in ${profile.iepSystem})
MLL / interpreter: ${student.hasMLL ? `yes · ${student.homeLanguage || 'language TBD'}${student.interpreterNeeded ? ' · interpreter needed' : ''}` : 'n/a'}

CHECKLIST
${checklist}

RECENT PROBES
${probes.length ? probes.map((p) => `· ${p.date} ${p.label} — ${p.scorePercent}%`).join('\n') : '· none stored'}

RECENT SOAP / SERVICE DATES
${soap.length ? soap.map((n) => `· ${n.date}`).join('\n') : '· none stored'}

NOTES
${packet.notes || '—'}

—— INTERACTIVE AGENDA ——
${filledAgenda}

—— TEMPLATE REFERENCE ——
${agendaFallback}

—— NOM DRAFT (Companion: finalize in ${profile.iepSystem}) ——
${nom}

Generated by PRISM Meeting Prep · no live Enrich sync · human review required`

    persist({ ...packet, packetText: text, checks: { ...packet.checks, agenda: true } })
    flash('Packet assembled — Copy or Print')
  }

  const doneCount = PREP_CHECKS.filter((c) => packet.checks[c.id]).length
  const agendaFilled = AGENDA_SECTIONS.filter((s) => (packet.agendaSections[s.id] || '').trim()).length

  return (
    <PageShell
      title="📋 Meeting Prep"
      description={`Interactive IEP agenda form with section headers ready to fill. NOM checklist (${nomDays}d). Companion: Copy into ${profile.iepSystem}. Drop your district template later and we’ll swap the headers.`}
    >
      {toast && (
        <div className="mb-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white">
          {toast}
        </div>
      )}

      <section
        className="mb-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card"
        style={{ borderTop: '4px solid var(--accent)' }}
      >
        <div className="grid gap-3 md:grid-cols-2">
          <label className="text-xs font-semibold">
            Student
            <select
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.studentId}
              onChange={(e) => selectStudent(e.target.value)}
            >
              <option value="">Select…</option>
              {students.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                  {s.meetingDate ? ` · meet ${s.meetingDate}` : ''}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs font-semibold">
            Meeting date
            <input
              type="date"
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.meetingDate}
              onChange={(e) => persist({ ...packet, meetingDate: e.target.value })}
            />
          </label>
          <label className="text-xs font-semibold md:col-span-2">
            Purpose
            <input
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
              value={packet.purpose}
              onChange={(e) => persist({ ...packet, purpose: e.target.value })}
            />
          </label>
        </div>

        <p className="mt-3 text-xs font-semibold">
          Prep checklist ({doneCount}/{PREP_CHECKS.length})
        </p>
        <ul className="mt-2 grid gap-1 sm:grid-cols-2">
          {PREP_CHECKS.map((c) => (
            <li key={c.id}>
              <label className="flex items-center gap-2 rounded-lg tint-slate px-2 py-1.5 text-xs">
                <input
                  type="checkbox"
                  checked={packet.checks[c.id]}
                  onChange={() => toggle(c.id)}
                />
                {c.label}
              </label>
            </li>
          ))}
        </ul>
      </section>

      <section
        className="mb-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card"
        style={{ borderTop: '4px solid var(--accent-h)' }}
      >
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <h2 className="font-heading text-sm font-bold">Interactive agenda</h2>
            <p className="text-[10px] text-[var(--subtext)]">
              Headers in place — type under each. {agendaFilled}/{AGENDA_SECTIONS.length} started.
              Upload your CCSD template anytime and we’ll match these sections.
            </p>
          </div>
        </div>

        <div className="mt-3 space-y-3">
          {AGENDA_SECTIONS.map((s, i) => {
            const tints = [
              'tint-lav',
              'tint-sky',
              'tint-mint',
              'tint-sun',
              'tint-pink',
              'tint-softorange',
              'tint-coral',
              'tint-lav',
              'tint-sky',
              'tint-mint',
            ]
            return (
              <label
                key={s.id}
                className={`block rounded-xl border border-[var(--border)] p-3 ${tints[i % tints.length]}`}
              >
                <span className="text-xs font-bold text-[var(--text)]">{s.title}</span>
                <textarea
                  className="mt-1.5 w-full rounded-lg border border-[var(--border)] bg-[var(--card-bg)] px-2 py-2 text-xs"
                  rows={2}
                  placeholder={s.placeholder}
                  value={packet.agendaSections[s.id] || ''}
                  onChange={(e) => setSection(s.id, e.target.value)}
                  disabled={!packet.studentId}
                />
              </label>
            )
          })}
        </div>

        <label className="mt-3 block text-xs font-semibold">
          Extra notes
          <textarea
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
            rows={2}
            value={packet.notes}
            onChange={(e) => persist({ ...packet, notes: e.target.value })}
          />
        </label>

        <div className="mt-3 flex flex-wrap gap-2">
          <button
            type="button"
            className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
            onClick={assemblePacket}
          >
            Assemble packet
          </button>
          <button
            type="button"
            className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
            disabled={!packet.packetText}
            onClick={() =>
              void navigator.clipboard.writeText(packet.packetText).then(() => flash('Copied'))
            }
          >
            Copy packet
          </button>
          <button
            type="button"
            className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
            disabled={!packet.packetText}
            onClick={() => window.print()}
          >
            Print
          </button>
          <Link to="/reminders" className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold">
            Enrich Reminders →
          </Link>
          <Link to="/planner" className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold">
            Weekly Planner →
          </Link>
        </div>

        {packet.packetText && (
          <pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--slate)] p-3 text-[10px]">
            {packet.packetText}
          </pre>
        )}
      </section>
    </PageShell>
  )
}
