/** LRE (Least Restrictive Environment) calculation — matches Samantha's IEP LRE tool. */

export const DEFAULT_SERVICE_ROWS = [
  'Occupational Therapy (OT)',
  'Mental Health (MH)',
  'Speech-Language Pathology (SLP)',
  'Academics — Math',
  'Academics — Reading',
  'Academics — Writing',
  'Physical Therapy (PT)',
] as const

export type LreBand = {
  id: 'least' | 'moderate' | 'most'
  label: string
  range: string
  description: string
}

export const LRE_BANDS: LreBand[] = [
  {
    id: 'least',
    label: 'Least Restrictive',
    range: '80–100%',
    description: 'Student spends ≥80% of time in general education',
  },
  {
    id: 'moderate',
    label: 'Moderate',
    range: '40–79%',
    description: 'Student spends 40–79% of time in general education',
  },
  {
    id: 'most',
    label: 'Most Restrictive',
    range: '0–39%',
    description: 'Student spends <40% of time in general education',
  },
]

export type LreInputs = {
  hoursPerDay: number
  daysPerWeek: number
  /** When set, overrides hours×days calculation (matches custom building schedules). */
  totalMinutesOverride?: number | null
  /** Weekly minutes OUTSIDE general education, by provider row */
  outsideMinutes: number[]
}

export type LreResult = {
  totalSchoolMinutes: number
  totalOutside: number
  totalInGe: number
  lrePercent: number
  band: LreBand
}

export function totalSchoolMinutes(
  hoursPerDay: number,
  daysPerWeek: number,
  override?: number | null,
): number {
  if (override != null && override > 0) return Math.round(override)
  const h = Math.max(0, hoursPerDay)
  const d = Math.max(0, daysPerWeek)
  return Math.round(h * 60 * d)
}

export function calculateLre(input: LreInputs): LreResult {
  const totalSchool = totalSchoolMinutes(
    input.hoursPerDay,
    input.daysPerWeek,
    input.totalMinutesOverride,
  )
  const totalOutside = input.outsideMinutes.reduce((sum, n) => sum + Math.max(0, Number(n) || 0), 0)
  const totalInGe = Math.max(0, totalSchool - totalOutside)
  const lrePercent = totalSchool > 0 ? (totalInGe / totalSchool) * 100 : 0

  let band = LRE_BANDS[2]
  if (lrePercent >= 80) band = LRE_BANDS[0]
  else if (lrePercent >= 40) band = LRE_BANDS[1]

  return {
    totalSchoolMinutes: totalSchool,
    totalOutside,
    totalInGe,
    lrePercent,
    band,
  }
}

export function formatLreReport(opts: {
  studentName: string
  school: string
  grade: string
  date: string
  iepReview: string
  providers: { name: string; minutes: number; notes: string }[]
  hoursPerDay: number
  daysPerWeek: number
  result: LreResult
}): string {
  const { result: r } = opts
  const lines = [
    'LRE CALCULATOR — Least Restrictive Environment',
    'IEP Team Planning Tool (PRISM)',
    '',
    'SECTION 1 — STUDENT INFORMATION',
    `Student Name: ${opts.studentName || '—'}`,
    `School: ${opts.school || '—'}`,
    `Grade: ${opts.grade || '—'}`,
    `Date: ${opts.date || '—'}`,
    `IEP Annual Review Date: ${opts.iepReview || '—'}`,
    '',
    'SECTION 2 — SERVICE PROVIDER MINUTES (OUTSIDE general education only)',
    ...opts.providers.map(
      (p) =>
        `${p.name}: ${p.minutes || 0} min/week${p.notes ? ` — ${p.notes}` : ''}`,
    ),
    `TOTAL outside GE: ${r.totalOutside}`,
    '',
    'SECTION 3 — SCHOOL WEEK',
    `Hours/day: ${opts.hoursPerDay}`,
    `Days/week: ${opts.daysPerWeek}`,
    `Total school minutes/week: ${r.totalSchoolMinutes}`,
    '',
    'SECTION 4 — RESULTS',
    `Minutes outside GE: ${r.totalOutside}`,
    `Minutes IN GE: ${r.totalInGe}`,
    `LRE % (time in GE): ${r.lrePercent.toFixed(1)}%`,
    `LRE Band: ${r.band.range} (${r.band.label})`,
    '',
    'Notes: Do NOT count push-in services delivered inside general education.',
    'IDEA requires education in the least restrictive environment appropriate.',
    'Companion: copy into Enrich / SoR — PRISM does not live-sync.',
    '',
    'Generated by PRISM Quick Tools',
  ]
  return lines.join('\n')
}
