/** Browser-only session / progress notes (FERPA — never commit PHI). */

export type SoapNote = {
  id: string
  studentId: string
  date: string
  subjective: string
  objective: string
  assessment: string
  plan: string
  updatedAt: string
}

export type ProgressProbe = {
  studentId: string
  label: string
  lastScore: number
  scores: number[]
  updatedAt: string
}

const SOAP_KEY = 'prism_soap_notes_v1'
const PROGRESS_KEY = 'prism_progress_probes_v1'

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key)
    if (!raw) return fallback
    return (JSON.parse(raw) as T) ?? fallback
  } catch {
    return fallback
  }
}

export function loadSoapNotes(): SoapNote[] {
  const list = readJson<SoapNote[]>(SOAP_KEY, [])
  return Array.isArray(list) ? list : []
}

export function saveSoapNotes(list: SoapNote[]) {
  localStorage.setItem(SOAP_KEY, JSON.stringify(list))
}

export function loadProgressProbes(): ProgressProbe[] {
  const list = readJson<ProgressProbe[]>(PROGRESS_KEY, [])
  return Array.isArray(list) ? list : []
}

export function saveProgressProbes(list: ProgressProbe[]) {
  localStorage.setItem(PROGRESS_KEY, JSON.stringify(list))
}

export function formatSoapForEnrich(note: SoapNote, studentName: string, hoursPolicy: number): string {
  return `SERVICE LOG / SOAP — Copy into Enrich (within ${hoursPolicy}h of session)

Student: ${studentName}
Session date: ${note.date}

S (Subjective): ${note.subjective || '—'}
O (Objective): ${note.objective || '—'}
A (Assessment): ${note.assessment || '—'}
P (Plan): ${note.plan || '—'}

Generated by PRISM · human review required · no live Enrich sync`
}
