/** Enrich reminder checklists — browser-only; no live Enrich sync. */

export type ReminderChecklist = {
  studentId: string
  /** step label → completed ISO date or empty */
  steps: Record<string, string>
  nomSentDate: string
  notes: string
  updatedAt: string
}

const KEY = 'prism_enrich_reminders_v1'

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key)
    if (!raw) return fallback
    return (JSON.parse(raw) as T) ?? fallback
  } catch {
    return fallback
  }
}

export function loadReminderChecklists(): ReminderChecklist[] {
  const list = readJson<ReminderChecklist[]>(KEY, [])
  return Array.isArray(list) ? list : []
}

export function saveReminderChecklists(list: ReminderChecklist[]) {
  localStorage.setItem(KEY, JSON.stringify(list))
}

export function getOrCreateChecklist(
  list: ReminderChecklist[],
  studentId: string,
  sequence: string[],
): ReminderChecklist {
  const existing = list.find((c) => c.studentId === studentId)
  if (existing) {
    const steps = { ...existing.steps }
    for (const s of sequence) {
      if (!(s in steps)) steps[s] = ''
    }
    return { ...existing, steps }
  }
  const steps: Record<string, string> = {}
  for (const s of sequence) steps[s] = ''
  return {
    studentId,
    steps,
    nomSentDate: '',
    notes: '',
    updatedAt: new Date().toISOString(),
  }
}

export function formatChecklistForEnrich(
  studentName: string,
  checklist: ReminderChecklist,
  sequence: string[],
  iepSystem: string,
): string {
  const lines = sequence.map((step) => {
    const done = checklist.steps[step]
    return `- [${done ? 'x' : ' '}] ${step}${done ? ` (${done})` : ''}`
  })
  return `ENRICH REMINDER CHECKLIST — Copy into ${iepSystem} notes (no live sync)

Student: ${studentName}
NOM sent date: ${checklist.nomSentDate || '—'}

Finalize / workflow steps:
${lines.join('\n')}

Notes: ${checklist.notes || '—'}

Generated by PRISM · human review required`
}
