import { useState } from 'react'
import type { DistrictProfile } from '../../lib/district-profiles/types'

type Props = {
  profile: DistrictProfile
  onFlash: (msg: string) => void
}

export function EsyWizard({ profile, onFlash }: Props) {
  const [student, setStudent] = useState('')
  const [regression, setRegression] = useState('')
  const [recoup, setRecoup] = useState('')
  const [services, setServices] = useState('')
  const [decision, setDecision] = useState<'Recommend ESY' | 'Do not recommend ESY' | 'Team undecided'>(
    'Team undecided',
  )

  function build() {
    const text = `ESY DETERMINATION SCAFFOLD — ${profile.name}
(Companion draft — enter official determination in ${profile.iepSystem}. No live sync.)

Student: ${student || 'TBD'}
Decision lean: ${decision}

1) Regression risk / nature & severity of disability
${regression || '—'}

2) Recoupment concerns after breaks
${recoup || '—'}

3) Proposed ESY services / frequency / setting
${services || '—'}

4) Team next steps
- Review progress data and prior break patterns
- Document parent input
- If recommending ESY: update IEP / PWN as required
- Enter final decision in ${profile.iepSystem}

Generated by PRISM Action Builder`
    return text
  }

  return (
    <div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--slate)] p-4">
      <h3 className="font-heading text-sm font-bold">ESY determination wizard</h3>
      <p className="mt-1 text-[10px] text-[var(--subtext)]">
        Feature flag <code>esy</code> is on for this district profile. Structured scaffold — AI optional
        later.
      </p>
      <div className="mt-3 grid gap-2 md:grid-cols-2">
        <label className="text-xs font-semibold md:col-span-2">
          Student
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={student}
            onChange={(e) => setStudent(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold">
          Lean
          <select
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={decision}
            onChange={(e) => setDecision(e.target.value as typeof decision)}
          >
            <option>Recommend ESY</option>
            <option>Do not recommend ESY</option>
            <option>Team undecided</option>
          </select>
        </label>
        <label className="text-xs font-semibold md:col-span-2">
          Regression risk notes
          <textarea
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
            rows={2}
            value={regression}
            onChange={(e) => setRegression(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold md:col-span-2">
          Recoupment notes
          <textarea
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
            rows={2}
            value={recoup}
            onChange={(e) => setRecoup(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold md:col-span-2">
          Proposed services
          <textarea
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
            rows={2}
            value={services}
            onChange={(e) => setServices(e.target.value)}
          />
        </label>
      </div>
      <button
        type="button"
        className="mt-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
        onClick={() =>
          void navigator.clipboard.writeText(build()).then(() => onFlash('ESY scaffold copied'))
        }
      >
        Copy ESY scaffold
      </button>
      <pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-white p-3 text-[10px]">
        {build()}
      </pre>
    </div>
  )
}

export function TransportWizard({ profile, onFlash }: Props) {
  const [student, setStudent] = useState('')
  const [reason, setReason] = useState('Specialized transportation related to disability')
  const [pickup, setPickup] = useState('')
  const [dropoff, setDropoff] = useState('')
  const [equipment, setEquipment] = useState('')
  const [aide, setAide] = useState(false)

  function build() {
    return `TRANSPORTATION REQUEST — ${profile.name}
(Companion draft — finalize in ${profile.iepSystem} / transport system. No live sync.)

Student: ${student || 'TBD'}
Reason: ${reason}
Pickup: ${pickup || 'TBD'}
Drop-off: ${dropoff || 'TBD'}
Equipment / accessibility: ${equipment || 'None noted'}
Aide / attendant needed: ${aide ? 'YES' : 'No'}

Checklist
[ ] Related service / IEP team discussion documented
[ ] Safety / medical considerations attached if needed
[ ] Parent contacted
[ ] Enter request in official transport / ${profile.iepSystem} workflow

Generated by PRISM Action Builder`
  }

  return (
    <div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--slate)] p-4">
      <h3 className="font-heading text-sm font-bold">Transportation request wizard</h3>
      <div className="mt-3 grid gap-2 md:grid-cols-2">
        <label className="text-xs font-semibold">
          Student
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={student}
            onChange={(e) => setStudent(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold">
          Reason
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={reason}
            onChange={(e) => setReason(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold">
          Pickup
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={pickup}
            onChange={(e) => setPickup(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold">
          Drop-off
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={dropoff}
            onChange={(e) => setDropoff(e.target.value)}
          />
        </label>
        <label className="text-xs font-semibold md:col-span-2">
          Equipment / notes
          <input
            className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
            value={equipment}
            onChange={(e) => setEquipment(e.target.value)}
          />
        </label>
        <label className="flex items-center gap-2 text-xs font-semibold">
          <input type="checkbox" checked={aide} onChange={(e) => setAide(e.target.checked)} />
          Aide / attendant needed
        </label>
      </div>
      <button
        type="button"
        className="mt-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
        onClick={() =>
          void navigator.clipboard.writeText(build()).then(() => onFlash('Transport request copied'))
        }
      >
        Copy transport request
      </button>
      <pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-white p-3 text-[10px]">
        {build()}
      </pre>
    </div>
  )
}
