import { useState } from 'react'
import { useStudents } from '../../lib/students/useStudents'
import { chat } from '../../lib/ai/client'
import {
  buildLocalSocialStory,
  loadMaterials,
  saveMaterials,
  type SavedMaterial,
} from '../../lib/classroom-materials/store'

type Props = {
  onFlash: (msg: string) => void
}

type MatTab = 'token' | 'schedule' | 'social' | 'comm' | 'saved'

const SHAPES = ['⭐ Stars', '🟢 Circles', '💎 Diamonds'] as const

export function ClassroomMaterialsPanel({ onFlash }: Props) {
  const { students } = useStudents()
  const [matTab, setMatTab] = useState<MatTab>('token')
  const [saved, setSaved] = useState<SavedMaterial[]>(() => loadMaterials())

  // Token
  const [tokenStudent, setTokenStudent] = useState('')
  const [tokenCount, setTokenCount] = useState(5)
  const [reward, setReward] = useState('5 min preferred activity')
  const [shape, setShape] = useState<(typeof SHAPES)[number]>('⭐ Stars')

  // Schedule
  const [schedStudent, setSchedStudent] = useState('')
  const [schedType, setSchedType] = useState('Full Day')
  const [activities, setActivities] = useState('Arrival\nMorning meeting\nWork time\nBreak\nDismissal')

  // Social
  const [socialStudent, setSocialStudent] = useState('')
  const [topic, setTopic] = useState('Taking turns')
  const [story, setStory] = useState('')
  const [busy, setBusy] = useState(false)

  // Comm board
  const [commStudent, setCommStudent] = useState('')
  const [commWords, setCommWords] = useState(
    'I want\nmore\nstop\nhelp\ngo\nbathroom\ndrink\neat',
  )

  function persist(item: SavedMaterial) {
    const next = [item, ...saved].slice(0, 40)
    setSaved(next)
    saveMaterials(next)
    onFlash('Saved to browser materials library')
  }

  function studentName(id: string) {
    return students.find((s) => s.id === id)?.name || ''
  }

  function saveToken() {
    const name = studentName(tokenStudent)
    const body = `TOKEN BOARD — ${name || 'Student'}
Shape: ${shape}
Tokens needed: ${tokenCount}
Reward: ${reward}

${Array.from({ length: tokenCount }, (_, i) => `[ ${i + 1} ]`).join('  ')}

I am working for: ${reward}
Generated by PRISM Classroom Materials`
    persist({
      id: `mat-${Date.now()}`,
      kind: 'token',
      title: `Token board (${tokenCount})`,
      studentName: name,
      body,
      createdAt: new Date().toISOString(),
    })
  }

  function saveSchedule() {
    const name = studentName(schedStudent)
    const lines = activities
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
    const body = `VISUAL SCHEDULE — ${schedType}
Student: ${name || 'TBD'}

${lines.map((l, i) => `${i + 1}. ${l}`).join('\n')}

Generated by PRISM Classroom Materials`
    persist({
      id: `mat-${Date.now()}`,
      kind: 'schedule',
      title: `${schedType} schedule`,
      studentName: name,
      body,
      createdAt: new Date().toISOString(),
    })
  }

  function generateLocalStory() {
    const name = studentName(socialStudent)
    const text = buildLocalSocialStory(name, topic)
    setStory(text)
    onFlash('Local social story ready (works offline)')
  }

  async function polishStory() {
    if (!story.trim()) {
      generateLocalStory()
    }
    setBusy(true)
    const name = studentName(socialStudent)
    const base = story || buildLocalSocialStory(name, topic)
    const res = await chat([
      {
        role: 'system',
        content:
          'You write short, affirming social stories for elementary students. Keep language simple. Return only the story.',
      },
      {
        role: 'user',
        content: `Polish this social story for ${name || 'a student'} about "${topic}":\n\n${base}`,
      },
    ])
    setBusy(false)
    if (res.error && !res.content) {
      setStory(base)
      onFlash(`${res.error} — kept offline draft`)
      return
    }
    setStory(res.content || base)
    onFlash(res.error ? `AI note: ${res.error}` : 'AI polish ready')
  }

  function saveStory() {
    const name = studentName(socialStudent)
    const body = story || buildLocalSocialStory(name, topic)
    persist({
      id: `mat-${Date.now()}`,
      kind: 'social',
      title: `Social story: ${topic}`,
      studentName: name,
      body,
      createdAt: new Date().toISOString(),
    })
  }

  function saveCommBoard() {
    const name = studentName(commStudent)
    const words = commWords
      .split('\n')
      .map((w) => w.trim())
      .filter(Boolean)
    const body = `COMMUNICATION BOARD — ${name || 'Student'}
Core + context vocabulary:

${words.map((w, i) => `${i + 1}. ${w}`).join('\n')}

Use with speech: click/tap cells in classroom; TTS vendor pending Azure /api/ai-speak.
Generated by PRISM Classroom Materials`
    persist({
      id: `mat-${Date.now()}`,
      kind: 'comm',
      title: 'Communication board',
      studentName: name,
      body,
      createdAt: new Date().toISOString(),
    })
  }

  return (
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
      <h2 className="font-heading text-sm font-bold">Classroom Materials Studio</h2>
      <p className="mt-1 text-xs text-[var(--subtext)]">
        Token boards, visual schedules, and social stories — offline-first. AI polish is optional when
        `/api/ai-chat` is available.
      </p>

      <div className="mt-3 flex flex-wrap gap-2">
        {(
          [
            ['token', 'Token board'],
            ['schedule', 'Visual schedule'],
            ['social', 'Social story'],
            ['comm', 'Comm board'],
            ['saved', 'Saved'],
          ] as const
        ).map(([id, label]) => (
          <button
            key={id}
            type="button"
            onClick={() => setMatTab(id)}
            className={`rounded-lg border px-3 py-1.5 text-xs font-semibold ${
              matTab === id
                ? 'border-[var(--accent)] bg-[var(--accent)] text-white'
                : 'border-[var(--border)] text-[var(--subtext)]'
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {matTab === 'token' && (
        <div className="mt-4 space-y-3">
          <div className="grid gap-3 md:grid-cols-2">
            <label className="text-xs font-semibold">
              Student
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={tokenStudent}
                onChange={(e) => setTokenStudent(e.target.value)}
              >
                <option value="">Select…</option>
                {students.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="text-xs font-semibold">
              Tokens needed
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={tokenCount}
                onChange={(e) => setTokenCount(Number(e.target.value))}
              >
                {[3, 5, 8, 10].map((n) => (
                  <option key={n} value={n}>
                    {n}
                  </option>
                ))}
              </select>
            </label>
            <label className="text-xs font-semibold">
              Reward
              <input
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={reward}
                onChange={(e) => setReward(e.target.value)}
              />
            </label>
            <label className="text-xs font-semibold">
              Token shape
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={shape}
                onChange={(e) => setShape(e.target.value as (typeof SHAPES)[number])}
              >
                {SHAPES.map((s) => (
                  <option key={s}>{s}</option>
                ))}
              </select>
            </label>
          </div>
          <div className="flex flex-wrap gap-2 rounded-xl bg-[var(--slate)] p-4">
            {Array.from({ length: tokenCount }, (_, i) => (
              <div
                key={i}
                className="flex h-12 w-12 items-center justify-center rounded-full border-2 border-dashed border-[var(--border)] bg-white text-lg"
              >
                {shape.split(' ')[0]}
              </div>
            ))}
          </div>
          <p className="text-xs font-semibold">Working for: {reward}</p>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
              onClick={saveToken}
            >
              Save token board
            </button>
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              onClick={() => window.print()}
            >
              Print
            </button>
          </div>
        </div>
      )}

      {matTab === 'schedule' && (
        <div className="mt-4 space-y-3">
          <div className="grid gap-3 md:grid-cols-2">
            <label className="text-xs font-semibold">
              Student
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={schedStudent}
                onChange={(e) => setSchedStudent(e.target.value)}
              >
                <option value="">Select…</option>
                {students.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="text-xs font-semibold">
              Schedule type
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={schedType}
                onChange={(e) => setSchedType(e.target.value)}
              >
                {['Full Day', 'Morning Routine', 'Session', 'Transition'].map((t) => (
                  <option key={t}>{t}</option>
                ))}
              </select>
            </label>
            <label className="text-xs font-semibold md:col-span-2">
              Activities (one per line)
              <textarea
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
                rows={5}
                value={activities}
                onChange={(e) => setActivities(e.target.value)}
              />
            </label>
          </div>
          <div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">
            {activities
              .split('\n')
              .map((l) => l.trim())
              .filter(Boolean)
              .map((l, i) => (
                <div
                  key={`${l}-${i}`}
                  className="rounded-xl border border-[var(--border)] bg-[var(--sky)] px-3 py-4 text-center text-xs font-bold"
                >
                  {i + 1}. {l}
                </div>
              ))}
          </div>
          <button
            type="button"
            className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
            onClick={saveSchedule}
          >
            Save schedule
          </button>
        </div>
      )}

      {matTab === 'social' && (
        <div className="mt-4 space-y-3">
          <div className="grid gap-3 md:grid-cols-2">
            <label className="text-xs font-semibold">
              Student
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={socialStudent}
                onChange={(e) => setSocialStudent(e.target.value)}
              >
                <option value="">Select…</option>
                {students.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="text-xs font-semibold">
              Topic
              <input
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
              />
            </label>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              onClick={generateLocalStory}
            >
              Generate offline draft
            </button>
            <button
              type="button"
              disabled={busy}
              className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-60"
              onClick={() => void polishStory()}
            >
              {busy ? 'Polishing…' : 'Optional AI polish'}
            </button>
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              onClick={saveStory}
            >
              Save story
            </button>
            <button
              type="button"
              className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
              disabled={!story}
              onClick={() => void navigator.clipboard.writeText(story).then(() => onFlash('Copied'))}
            >
              Copy
            </button>
          </div>
          <pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--slate)] p-3 text-xs">
            {story || 'Generate a draft to preview.'}
          </pre>
        </div>
      )}

      {matTab === 'comm' && (
        <div className="mt-4 space-y-3">
          <label className="block text-xs font-semibold">
            Student
            <select
              className="mt-1 w-full max-w-xs rounded-lg border border-[var(--border)] px-2 py-2"
              value={commStudent}
              onChange={(e) => setCommStudent(e.target.value)}
            >
              <option value="">Select…</option>
              {students.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <label className="block text-xs font-semibold">
            Vocabulary (one word/phrase per line)
            <textarea
              className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-xs"
              rows={5}
              value={commWords}
              onChange={(e) => setCommWords(e.target.value)}
            />
          </label>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            {commWords
              .split('\n')
              .map((w) => w.trim())
              .filter(Boolean)
              .map((w, i) => (
                <button
                  key={`${w}-${i}`}
                  type="button"
                  className="rounded-xl border border-[var(--border)] bg-[var(--sky)] px-2 py-4 text-center text-xs font-bold"
                  onClick={() => onFlash(`Selected: ${w} (TTS pending Azure /api/ai-speak)`)}
                >
                  {w}
                </button>
              ))}
          </div>
          <button
            type="button"
            className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
            onClick={saveCommBoard}
          >
            Save communication board
          </button>
        </div>
      )}

      {matTab === 'saved' && (
        <div className="mt-4 space-y-2">
          {!saved.length && (
            <p className="text-xs text-[var(--subtext)]">No saved materials yet (browser only).</p>
          )}
          {saved.map((m) => (
            <div key={m.id} className="rounded-xl border border-[var(--border)] p-3 text-xs">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <strong>
                  {m.title}
                  {m.studentName ? ` — ${m.studentName}` : ''}
                </strong>
                <button
                  type="button"
                  className="font-semibold text-[var(--accent)]"
                  onClick={() => void navigator.clipboard.writeText(m.body).then(() => onFlash('Copied'))}
                >
                  Copy
                </button>
              </div>
              <p className="mt-1 text-[10px] text-[var(--subtext)]">
                {m.kind} · {new Date(m.createdAt).toLocaleString()}
              </p>
            </div>
          ))}
        </div>
      )}
    </section>
  )
}
