import { useEffect, useMemo, useState } from 'react'
import { PageShell } from '../../components/PageShell'
import { useDistrictProfile } from '../../lib/district-profiles/useDistrictProfile'
import { useStudents } from '../../lib/students/useStudents'
import {
  allForms,
  fillTemplateBody,
  loadCustomTemplates,
  loadTemplateInstances,
  readSuiteMode,
  saveCustomTemplates,
  saveTemplateInstances,
  suiteModeNote,
  type FormTemplate,
  type SuiteMode,
  type TemplateInstance,
} from '../../lib/templates/catalog'
import { FieldTip } from '../../lib/help-assist/FieldTip'
import { storage } from '../../lib/storage'
import { chat } from '../../lib/ai/client'

const CATS = ['All', 'IEP', '504', 'MLL', 'Compliance', 'Behavior', 'Communication', 'Assessment', 'Custom'] as const

export function TemplatesPage() {
  const { students } = useStudents()
  const { profile } = useDistrictProfile()
  const [mode] = useState<SuiteMode>(() => readSuiteMode())
  const [custom, setCustom] = useState<FormTemplate[]>(() => loadCustomTemplates())
  const [instances, setInstances] = useState<TemplateInstance[]>(() => loadTemplateInstances())
  const [cat, setCat] = useState<string>('All')
  const [activeId, setActiveId] = useState<string | null>(null)
  const [studentId, setStudentId] = useState('')
  const [body, setBody] = useState('')
  const [toast, setToast] = useState('')
  const [createName, setCreateName] = useState('')
  const [createCat, setCreateCat] = useState('IEP')
  const [createBody, setCreateBody] = useState('')
  const [tab, setTab] = useState<'library' | 'drafts' | 'creator'>('library')

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const [storedInstances, storedCustom] = await Promise.all([
          storage.getTemplateInstances(),
          storage.getCustomTemplates(),
        ])
        if (cancelled) return
        if (storedInstances.length) setInstances(storedInstances)
        if (storedCustom.length) setCustom(storedCustom)
      } catch {
        /* keep sync localStorage seed */
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const forms = useMemo(() => allForms(custom), [custom])
  const active = forms.find((f) => f.id === activeId) || null
  const filtered = useMemo(() => {
    if (cat === 'Custom') return forms.filter((f) => f.custom)
    if (cat !== 'All') return forms.filter((f) => f.cat === cat)
    return forms
  }, [forms, cat])

  function flash(msg: string) {
    setToast(msg)
    window.setTimeout(() => setToast(''), 2200)
  }

  function selectTemplate(form: FormTemplate) {
    setActiveId(form.id)
    setBody(form.body)
    setTab('library')
    flash(`Loaded ${form.name}`)
  }

  function fill() {
    if (!active) {
      flash('Select a template first')
      return
    }
    const s = students.find((x) => x.id === studentId) || null
    const text = `${fillTemplateBody(active.body, s)}\n\n${suiteModeNote(mode, profile.iepSystem)}\nGenerated by PRISM · Reflect the Whole Human\n`
    setBody(text)
    flash(s ? `Filled for ${s.name}` : 'Filled with placeholders')
  }

  async function copyBody(text = body) {
    try {
      await navigator.clipboard.writeText(text)
      flash(mode === 'companion' ? `Copied — paste into ${profile.iepSystem}` : 'Copied')
    } catch {
      flash('Copy failed — select text manually')
    }
  }

  function saveDraft() {
    if (mode !== 'standalone') {
      flash('Switch Suite Mode to Standalone in live deploy Admin to save drafts — or Copy')
      return
    }
    if (!body.trim()) {
      flash('Nothing to save')
      return
    }
    const s = students.find((x) => x.id === studentId)
    const now = new Date().toISOString()
    const inst: TemplateInstance = {
      id: `inst-${Date.now()}`,
      formId: active?.id || 'custom',
      type: active?.name || 'Draft',
      studentId: studentId || null,
      studentName: s?.name || '',
      title: `${active?.name || 'Draft'}${s ? ` — ${s.name}` : ''}`,
      body,
      status: 'draft',
      createdAt: now,
      updatedAt: now,
    }
    const next = [inst, ...instances]
    setInstances(next)
    saveTemplateInstances(next)
    void storage.saveTemplateInstances(next)
    flash('Saved district draft')
    setTab('drafts')
  }

  function saveCustom() {
    if (!createName.trim() || !createBody.trim()) {
      flash('Name and body required')
      return
    }
    const t: FormTemplate = {
      id: `custom-${Date.now()}`,
      name: createName.trim(),
      cat: createCat,
      status: 'Custom',
      body: createBody,
      custom: true,
    }
    const next = [...custom, t]
    setCustom(next)
    saveCustomTemplates(next)
    void storage.saveCustomTemplates(next)
    setCreateName('')
    setCreateBody('')
    flash('District template saved')
    setTab('library')
    setCat('Custom')
  }

  async function aiPolish() {
    if (!body.trim()) {
      flash('Fill or paste a draft first')
      return
    }
    flash('Generating with /api/ai-chat…')
    const s = students.find((x) => x.id === studentId)
    const res = await chat([
      {
        role: 'system',
        content: `You are a special education document assistant for ${profile.name}. Improve clarity while keeping IDEA-compliant language. Return only the revised document text.`,
      },
      {
        role: 'user',
        content: `Revise this ${active?.name || 'draft'} for ${s ? s.name : 'the student'}:\n\n${body}`,
      },
    ])
    if (res.error && !res.content) {
      flash(res.error)
      return
    }
    if (res.content) setBody(res.content)
    flash(res.error ? `AI returned with note: ${res.error}` : 'AI draft ready')
  }

  return (
    <PageShell
      title="🎨 Templates & Forms"
      description="Forms Library with student placeholder fill. Companion = Copy into SoR; Standalone = save district drafts (same localStorage keys as deploy/)."
    >
      <p className="mb-2 text-xs text-[var(--subtext)]">
        {mode === 'standalone' ? (
          <>
            Standalone suite: fill a form, then <strong>Save as district draft</strong> (browser /
            Graph when configured). Copy/Print still available.
          </>
        ) : (
          <>
            Companion mode: prepare drafts here, then <strong>Copy</strong> into {profile.iepSystem}.
            PRISM does not live-sync.
          </>
        )}
      </p>
      <FieldTip tipId="templates-suite" className="mb-3" />

      {toast && (
        <div className="mb-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white">
          {toast}
        </div>
      )}

      <div className="mb-4 flex flex-wrap gap-2">
        {(
          [
            ['library', 'Forms Library'],
            ['drafts', 'Saved Drafts'],
            ['creator', 'Template Creator'],
          ] as const
        ).map(([id, label]) => (
          <button
            key={id}
            type="button"
            onClick={() => setTab(id)}
            className={`rounded-lg border px-3 py-1.5 text-xs font-semibold ${
              tab === id
                ? 'border-[var(--accent)] bg-[var(--accent)] text-white'
                : 'border-[var(--border)] bg-[var(--card-bg)] text-[var(--subtext)]'
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {tab === 'library' && (
        <>
          <div className="mb-3 flex flex-wrap gap-2">
            {CATS.map((c) => (
              <button
                key={c}
                type="button"
                onClick={() => setCat(c)}
                className={`rounded-lg border px-3 py-1.5 text-xs font-semibold ${
                  cat === c
                    ? 'border-[var(--accent)] bg-[var(--accent)] text-white'
                    : 'border-[var(--border)] bg-[var(--card-bg)] text-[var(--subtext)]'
                }`}
              >
                {c}
              </button>
            ))}
          </div>

          <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {filtered.map((f) => (
              <div
                key={f.id}
                className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card"
              >
                <h3 className="text-sm font-bold">{f.name}</h3>
                <div className="mt-1 flex flex-wrap gap-1">
                  <span className="rounded-full bg-[var(--sky)] px-2 py-0.5 text-[10px] font-semibold">
                    {f.cat}
                  </span>
                  <span className="rounded-full bg-green-100 px-2 py-0.5 text-[10px] font-semibold text-green-800">
                    {f.status}
                  </span>
                  {f.custom && (
                    <span className="rounded-full bg-[var(--lav)] px-2 py-0.5 text-[10px] font-semibold">
                      District
                    </span>
                  )}
                </div>
                <button
                  type="button"
                  className="mt-3 rounded-lg border border-[var(--accent)] px-3 py-1.5 text-xs font-semibold text-[var(--accent)]"
                  onClick={() => selectTemplate(f)}
                >
                  Use Template
                </button>
              </div>
            ))}
          </div>

          <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
            <h2 className="font-heading text-sm font-bold">Draft from template</h2>
            <p className="mt-1 text-xs text-[var(--subtext)]">
              Active: <strong className="text-[var(--text)]">{active?.name || '—'}</strong>
            </p>
            <div className="mt-3 grid gap-3 md:grid-cols-2">
              <label className="text-xs font-semibold">
                Student
                <select
                  className="mt-1 w-full rounded-lg border border-[var(--border)] bg-white px-2 py-2"
                  value={studentId}
                  onChange={(e) => setStudentId(e.target.value)}
                >
                  <option value="">Select student…</option>
                  {students.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name} ({s.grade})
                    </option>
                  ))}
                </select>
              </label>
            </div>
            <textarea
              className="mt-3 w-full rounded-xl border border-[var(--border)] bg-white p-3 font-mono text-xs"
              rows={14}
              value={body}
              onChange={(e) => setBody(e.target.value)}
              placeholder="Filled template will appear here…"
            />
            <div className="mt-3 flex flex-wrap gap-2">
              <button
                type="button"
                className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
                onClick={fill}
              >
                Fill with student data
              </button>
              <button
                type="button"
                className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold"
                onClick={() => copyBody()}
              >
                Copy
              </button>
              <button
                type="button"
                className="rounded-lg border border-[var(--accent)] px-3 py-2 text-xs font-semibold text-[var(--accent)]"
                onClick={() => void aiPolish()}
              >
                AI polish draft
              </button>
              {mode === 'standalone' && (
                <button
                  type="button"
                  className="rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
                  onClick={saveDraft}
                >
                  Save as district draft
                </button>
              )}
            </div>
          </section>
        </>
      )}

      {tab === 'drafts' && (
        <section className="space-y-2 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <h2 className="font-heading text-sm font-bold">Saved district drafts</h2>
          {!instances.length && <p className="text-xs text-[var(--subtext)]">No saved drafts yet.</p>}
          {instances.map((inst) => (
            <div key={inst.id} className="rounded-xl border border-[var(--border)] p-3">
              <p className="text-sm font-semibold">{inst.title}</p>
              <p className="text-xs text-[var(--subtext)]">
                {inst.studentName || 'No student'} ·{' '}
                {new Date(inst.updatedAt).toLocaleString('en-US', { timeZone: 'America/Denver' })}
              </p>
              <div className="mt-2 flex gap-2">
                <button
                  type="button"
                  className="rounded-lg border border-[var(--border)] px-2 py-1 text-xs font-semibold"
                  onClick={() => {
                    setActiveId(inst.formId)
                    setBody(inst.body)
                    setStudentId(inst.studentId || '')
                    setTab('library')
                  }}
                >
                  Open
                </button>
                <button
                  type="button"
                  className="rounded-lg border border-[var(--border)] px-2 py-1 text-xs font-semibold"
                  onClick={() => copyBody(inst.body)}
                >
                  Copy
                </button>
                <button
                  type="button"
                  className="rounded-lg border border-red-200 px-2 py-1 text-xs font-semibold text-red-600"
                  onClick={() => {
                    const next = instances.filter((x) => x.id !== inst.id)
                    setInstances(next)
                    saveTemplateInstances(next)
                    flash('Draft deleted')
                  }}
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
        </section>
      )}

      {tab === 'creator' && (
        <section className="rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] p-4 shadow-card">
          <h2 className="font-heading text-sm font-bold">Custom Template Creator</h2>
          <p className="mt-1 text-xs text-[var(--subtext)]">
            Placeholders: <code>{'{{name}}'}</code> <code>{'{{grade}}'}</code>{' '}
            <code>{'{{goals}}'}</code> <code>{'{{accommodations}}'}</code> <code>{'{{homeLanguage}}'}</code>{' '}
            <code>{'{{date}}'}</code>
          </p>
          <div className="mt-3 grid gap-3 md:grid-cols-2">
            <label className="text-xs font-semibold">
              Template name
              <input
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={createName}
                onChange={(e) => setCreateName(e.target.value)}
              />
            </label>
            <label className="text-xs font-semibold">
              Category
              <select
                className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2"
                value={createCat}
                onChange={(e) => setCreateCat(e.target.value)}
              >
                {['IEP', '504', 'MLL', 'Behavior', 'Assessment', 'Communication', 'Compliance'].map(
                  (c) => (
                    <option key={c}>{c}</option>
                  ),
                )}
              </select>
            </label>
          </div>
          <textarea
            className="mt-3 w-full rounded-xl border border-[var(--border)] p-3 font-mono text-xs"
            rows={8}
            value={createBody}
            onChange={(e) => setCreateBody(e.target.value)}
            placeholder="Template content…"
          />
          <button
            type="button"
            className="mt-3 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white"
            onClick={saveCustom}
          >
            Save Template
          </button>
        </section>
      )}
    </PageShell>
  )
}
